package main

import (
	"crypto/sha256"
	"fmt"
	"strconv"
	"strings"
)

// Stores parsed information for a single e-mail.
type singleMail struct {
	MailID   string `json:"mailID"`
	QueueID  string `json:"queueID"`
	Date     string `json:"date"`
	Time     string `json:"time"`
	From     string `json:"from"`
	HostFrom string `json:"hostFrom"`
	UserFrom string `json:"userFrom"`
	TypeFrom string `json:"typeFrom"`
	To       string `json:"to"`
	HostTo   string `json:"hostTo"`
	UserTo   string `json:"userTo"`
	TypeTo   string `json:"typeTo"`
	Size     int64  `json:"size"`
	Subject  string `json:"subject"`
}

// SetDate sets the Date value of a singleMail object.
// No additional parsing is done.
func (sm *singleMail) SetDate(date string) {
	sm.Date = date
}

// SetTime sets the Time value of a singleMail object.
// No additional parsing is done.
func (sm *singleMail) SetTime(time string) {
	sm.Time = time
}

// SetFrom sets the From value of a singleMail object.
// It also splits up the given address and populates the HostFrom and UserFrom values.
func (sm *singleMail) SetFrom(from string) {
	sm.From = from
	fromParts := strings.Split(from, `@`)
	sm.HostFrom = fromParts[1]
	sm.UserFrom = fromParts[0]
	sm.TypeFrom = sm.GetHostType(sm.HostFrom)
}

// SetTo sets the To value of a singleMail object.
// It also splits up the given address and populates the HostTo and UserTo values.
func (sm *singleMail) SetTo(to string) {
	sm.To = to
	toParts := strings.Split(to, `@`)
	sm.HostTo = toParts[1]
	sm.UserTo = toParts[0]
	sm.TypeTo = sm.GetHostType(sm.HostTo)
}

// SetSubject sets the Subject value of a singleMail object.
// No additional parsing is done.
func (sm *singleMail) SetSubject(subject string) {
	sm.Subject = subject
}

// SetSize sets the Size value of a singleMail object.
// No additional parsing - apart from converting the given string into an int - is done.
func (sm *singleMail) SetSize(size string) {
	mailSize, mailSizeErr := strconv.Atoi(size)
	if mailSizeErr != nil {
		sm.Size = -1
	}
	sm.Size = int64(mailSize)
}

// SetQueueID sets the QueueID value of a singleMail object.
// No additional parsing is done.
func (sm *singleMail) SetQueueID(queueID string) {
	sm.QueueID = queueID
}

// GenerateMailID computes and sets the MailID value of a singleMail object.
// The MailID is generated by sha256'ing a string consisting of the QueueID, Date, Time, From and To values. The values are seperated by spaces.
func (sm *singleMail) GenerateMailID() {
	idString := fmt.Sprintf("%s %s %s %s %s", sm.QueueID, sm.Date, sm.Time, sm.From, sm.To)
	mailID := sha256.Sum256([]byte(idString))
	sm.MailID = fmt.Sprintf("%x", mailID)
}

// GetPartnerKey returns the partner key of a singleMail object.
// The partner key is generated by sorting the host parts. If the host parts are equal, it is generated by sorting the full addresses.
func (sm *singleMail) GetPartnerKey() string {
	commPartnerA := sm.From
	commPartnerB := sm.To

	if sm.HostFrom == sm.HostTo {
		if sm.From > sm.To {
			commPartnerA = sm.To
			commPartnerB = sm.From
		}
	} else if sm.HostFrom > sm.HostTo {
		commPartnerA = sm.To
		commPartnerB = sm.From
	}

	return fmt.Sprintf("%s %s", commPartnerA, commPartnerB)
}

// GetHostType returns the type of a given host, either "internal" or "external".
// Internal hosts are defined by providing the matching CLI argument; every other host is considered as external.
func (sm *singleMail) GetHostType(host string) string {
	for _, intHost := range config.InternalHosts {
		if intHost == host {
			return "internal"
		}
	}
	return "external"
}
